// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpcboMc-UiGzwJzpwBgXgRv3rnLJsMSo',
    appId: '1:222415830271:android:4b164c831b7bfd288420ca',
    messagingSenderId: '222415830271',
    projectId: 'take-a-bite-10236',
    storageBucket: 'take-a-bite-10236.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8nVTRWPNVc3lkUZBmHlgRfyXx4fx6mAo',
    appId: '1:222415830271:ios:7b0dbb754047f4278420ca',
    messagingSenderId: '222415830271',
    projectId: 'take-a-bite-10236',
    storageBucket: 'take-a-bite-10236.appspot.com',
    iosBundleId: 'com.example.takeABite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8nVTRWPNVc3lkUZBmHlgRfyXx4fx6mAo',
    appId: '1:222415830271:ios:7b0dbb754047f4278420ca',
    messagingSenderId: '222415830271',
    projectId: 'take-a-bite-10236',
    storageBucket: 'take-a-bite-10236.appspot.com',
    iosBundleId: 'com.example.takeABite',
  );
}
